engines:
  eslint:
    enabled: true
    config:
      config: ./linting/eslint_base.yaml
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
exclude_paths:
  - "scripts/"
  - "testing/"
  - "configs/"
  - "src/**/*.spec.js"
ratings:
  paths:
    - "src/**/*.js"
